### ISSUE TITLE
tickets deserialized: Error("missing field `labels`", line: 1, column: 11162)

### ISSUE THREAD

**Issue by chrstnwhlrt** [moali87/jirust#123]
Hey there, great project!

I think there might be an issue with deserializing custom fields: 

![image](https://github.com/moali87/jirust/assets/866769/547030b4-524c-4df7-8dea-9579a79768db)

(or something like that)

It's a jira cloud environment and it crashes when opening any project

**Comment by moali87** [comment]
Hello, apologies for the delayed response.  I will look at it when I get a chance.   By any chance, if you were to pull a ticket with jira API, does it return labels for you?

**Comment by moali87** [comment]
The specified versions should now return an empty list or "None" for labels.  If this still doesn't work for you, please reopen issue, or ask me to reopen.

For further debugging, you could set `RUST_LOG` to `debug`, run `jirust  2> output.log`, and that should print debug messages to `output.log`
